"""Type definitions for the Livepasses SDK."""

from livepasses.types.common import (
    ApiError,
    ApiErrorCodes,
    PagedParams,
    PagedResponse,
    PaginationMetadata,
    ResponseMetadata,
)
from livepasses.types.passes import (
    AnalyticsInfo,
    BatchOperationInfo,
    BatchStatistics,
    BatchStatusResult,
    BulkUpdatePassesParams,
    BusinessContext,
    BusinessData,
    BusinessMetrics,
    CheckInParams,
    CouponContext,
    CustomerInfo,
    DeliveryDetail,
    EventContext,
    GenerateAndWaitOptions,
    GeneratePassesParams,
    GeneratedPass,
    GeneratedPassSummary,
    GlobalPassDto,
    ListPassesParams,
    LookupPassParams,
    LoyaltyContext,
    LoyaltyTransactionParams,
    PassDeliveryResult,
    PassGenerationOptions,
    PassGenerationResult,
    PassLookupResult,
    PassPlatform,
    PassPlatforms,
    PassRecipient,
    PassRedemptionResult,
    PassValidationResult,
    PersonalizationData,
    RedeemCouponParams,
    RedeemPassParams,
    RedemptionLocation,
    UnifiedBusinessData,
    UpdatePassParams,
)
from livepasses.types.templates import (
    CreateTemplateParams,
    ListTemplatesParams,
    TemplateDetail,
    TemplateListItem,
    UpdateTemplateParams,
)
from livepasses.types.webhooks import (
    CreateWebhookParams,
    Webhook,
    WebhookEventType,
)

__all__ = [
    # Common
    "ApiError",
    "ApiErrorCodes",
    "PagedParams",
    "PagedResponse",
    "PaginationMetadata",
    "ResponseMetadata",
    # Passes
    "AnalyticsInfo",
    "BatchOperationInfo",
    "BatchStatistics",
    "BatchStatusResult",
    "BulkUpdatePassesParams",
    "BusinessContext",
    "BusinessData",
    "BusinessMetrics",
    "CheckInParams",
    "CouponContext",
    "CustomerInfo",
    "DeliveryDetail",
    "EventContext",
    "GenerateAndWaitOptions",
    "GeneratePassesParams",
    "GeneratedPass",
    "GeneratedPassSummary",
    "GlobalPassDto",
    "ListPassesParams",
    "LookupPassParams",
    "LoyaltyContext",
    "LoyaltyTransactionParams",
    "PassDeliveryResult",
    "PassGenerationOptions",
    "PassGenerationResult",
    "PassLookupResult",
    "PassPlatform",
    "PassPlatforms",
    "PassRecipient",
    "PassRedemptionResult",
    "PassValidationResult",
    "PersonalizationData",
    "RedeemCouponParams",
    "RedeemPassParams",
    "RedemptionLocation",
    "UnifiedBusinessData",
    "UpdatePassParams",
    # Templates
    "CreateTemplateParams",
    "ListTemplatesParams",
    "TemplateDetail",
    "TemplateListItem",
    "UpdateTemplateParams",
    # Webhooks
    "CreateWebhookParams",
    "Webhook",
    "WebhookEventType",
]
