"""Livepasses - Official Python SDK for the Livepasses API."""

from livepasses.client import Livepasses
from livepasses.errors import (
    AuthenticationError,
    BusinessRuleError,
    ForbiddenError,
    LivepassesError,
    NotFoundError,
    QuotaExceededError,
    RateLimitError,
    ValidationError,
)
from livepasses.types import (
    AnalyticsInfo,
    ApiError,
    ApiErrorCodes,
    BatchOperationInfo,
    BatchStatistics,
    BatchStatusResult,
    BulkUpdatePassesParams,
    BusinessContext,
    BusinessData,
    BusinessMetrics,
    CheckInParams,
    CouponContext,
    CreateTemplateParams,
    CreateWebhookParams,
    CustomerInfo,
    DeliveryDetail,
    EventContext,
    GenerateAndWaitOptions,
    GeneratePassesParams,
    GeneratedPass,
    GeneratedPassSummary,
    GlobalPassDto,
    ListPassesParams,
    ListTemplatesParams,
    LookupPassParams,
    LoyaltyContext,
    LoyaltyTransactionParams,
    PagedParams,
    PagedResponse,
    PaginationMetadata,
    PassDeliveryResult,
    PassGenerationOptions,
    PassGenerationResult,
    PassLookupResult,
    PassPlatform,
    PassPlatforms,
    PassRecipient,
    PassRedemptionResult,
    PassValidationResult,
    PersonalizationData,
    RedeemCouponParams,
    RedeemPassParams,
    RedemptionLocation,
    ResponseMetadata,
    TemplateDetail,
    TemplateListItem,
    UnifiedBusinessData,
    UpdatePassParams,
    UpdateTemplateParams,
    Webhook,
    WebhookEventType,
)

__all__ = [
    # Client
    "Livepasses",
    # Errors
    "LivepassesError",
    "AuthenticationError",
    "ValidationError",
    "ForbiddenError",
    "NotFoundError",
    "RateLimitError",
    "QuotaExceededError",
    "BusinessRuleError",
    # Common types
    "ApiError",
    "ApiErrorCodes",
    "PagedParams",
    "PagedResponse",
    "PaginationMetadata",
    "ResponseMetadata",
    # Pass types
    "AnalyticsInfo",
    "BatchOperationInfo",
    "BatchStatistics",
    "BatchStatusResult",
    "BulkUpdatePassesParams",
    "BusinessContext",
    "BusinessData",
    "BusinessMetrics",
    "CheckInParams",
    "CouponContext",
    "CustomerInfo",
    "DeliveryDetail",
    "EventContext",
    "GenerateAndWaitOptions",
    "GeneratePassesParams",
    "GeneratedPass",
    "GeneratedPassSummary",
    "GlobalPassDto",
    "ListPassesParams",
    "LookupPassParams",
    "LoyaltyContext",
    "LoyaltyTransactionParams",
    "PassDeliveryResult",
    "PassGenerationOptions",
    "PassGenerationResult",
    "PassLookupResult",
    "PassPlatform",
    "PassPlatforms",
    "PassRecipient",
    "PassRedemptionResult",
    "PassValidationResult",
    "PersonalizationData",
    "RedeemCouponParams",
    "RedeemPassParams",
    "RedemptionLocation",
    "UnifiedBusinessData",
    "UpdatePassParams",
    # Template types
    "CreateTemplateParams",
    "ListTemplatesParams",
    "TemplateDetail",
    "TemplateListItem",
    "UpdateTemplateParams",
    # Webhook types
    "CreateWebhookParams",
    "Webhook",
    "WebhookEventType",
]

__version__ = "0.1.0"
